### ISSUE TITLE
Bug in Share page

### ISSUE THREAD

**Issue by Deepaklather** [MirRaonaq/AndroidBots#100]
There is a bug in this android application. After successfully login into the app. I clicked on share button. And then i entered blank spaces in building name, room number and description then the app stops working.

**Comment by MirRaonaq** [comment]
@Deepaklather which version of Android are you using? Currently, our app supports API 21-24. We will make Food Basket available for all API soon.

**Comment by Deepaklather** [comment]
I am using Android 6.0 version.
Your app working fine in my phone. But when we insert blank spaces in all
the fields of share Activity then only your app crashes? I know how to fix
it because we were facing the same problem in my android application.
