### ISSUE TITLE
Create an "About Food Basket" page

### ISSUE THREAD

**Issue by MirRaonaq** [MirRaonaq/AndroidBots#76]
All code will be done in a new .xml file created by you.

1. Create a new blank activity

2. Name it "about"

- Navigate to` about.xml`

3. Drag and drop a text box to the page from the "Palette"

4. Copy the "project description" from our README.md in our GitHub

5. Paste the description into the text box

**Comment by MirRaonaq** [comment]
Whoever is assigned to my task, feel free to contact me. I am willing to help and provide feedback.

**Comment by jonhiggins15** [comment]
Just completed

**Comment by MirRaonaq** [comment]
Great work!
