### ISSUE TITLE
How to enable login with username (Firebase)

### ISSUE THREAD

**Issue by KemoAli** [MirRaonaq/AndroidBots#94]
Firebase authentication with username. Currently you can login with full email address only (off course with a password) but how do I add "username" as an option?  #93

**Comment by KemoAli** [comment]
#93

**Comment by ConnorMulqueen** [comment]
Hey!

I'm assigned to this task and just watched your beta release video, I noticed that there is a 'Username' field in the video, does this mean the front end is implemented and I should just be working on the backend for this collaboration?

**Comment by KemoAli** [comment]
You can look at that file and that function to get an idea of what is going on! But the problem, I assumed is on the register page.  If two users use the same username during signup the first user's email gets overwritten by the second's user.

eg.
["kemokhan"] ---
                          |                      
                          |                          
                          ---["email"] = kemo@buffalo.edu

At login, i can either use my email (kemo@buffalo.edu) or username (kemokhan) to login

But what if another user used "kemokhan" as their username? That is going to override my email with whatever email they entered and that means I would no longer be able to login with "kemokhan"

So, the loginUserWithUserName has my implementation. But I think the problem is at the register page. The only thing you have to fix is to check at signup if a particular username is taken.

look for these
file:          Register.java 
function:  registerUser

Sorry that my initial explanation was not very clear.

here is a screenshot of the json structure

![firebase](https://user-images.githubusercontent.com/13828225/38899359-966dcdf6-4265-11e8-9e3e-64f59bceda1c.PNG)
